[2023-03-03 12:17:18,961] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: avg_product_price.spark_submit manual__2023-03-03T11:41:42.035156+00:00 [queued]>
[2023-03-03 12:17:19,035] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: avg_product_price.spark_submit manual__2023-03-03T11:41:42.035156+00:00 [queued]>
[2023-03-03 12:17:19,036] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-03 12:17:19,037] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-03-03 12:17:19,038] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-03 12:17:19,151] {taskinstance.py:1377} INFO - Executing <Task(SparkSubmitOperator): spark_submit> on 2023-03-03 11:41:42.035156+00:00
[2023-03-03 12:17:19,193] {standard_task_runner.py:52} INFO - Started process 1469 to run task
[2023-03-03 12:17:19,212] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'avg_product_price', 'spark_submit', 'manual__2023-03-03T11:41:42.035156+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/avg_product_price.py', '--cfg-path', '/tmp/tmp87gig2kd', '--error-file', '/tmp/tmpt6pqso6h']
[2023-03-03 12:17:19,225] {standard_task_runner.py:80} INFO - Job 12: Subtask spark_submit
[2023-03-03 12:17:19,691] {task_command.py:370} INFO - Running <TaskInstance: avg_product_price.spark_submit manual__2023-03-03T11:41:42.035156+00:00 [running]> on host 7f5e973bdd66
[2023-03-03 12:17:20,120] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ayyoub
AIRFLOW_CTX_DAG_ID=avg_product_price
AIRFLOW_CTX_TASK_ID=spark_submit
AIRFLOW_CTX_EXECUTION_DATE=2023-03-03T11:41:42.035156+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-03T11:41:42.035156+00:00
[2023-03-03 12:17:20,155] {base.py:68} INFO - Using connection ID 'spark-hadoop' for task execution.
[2023-03-03 12:17:20,159] {spark_submit.py:344} INFO - Spark-Submit cmd: spark-submit --master local[*] --name arrow-spark /hadoop-data/map_reduce/spark/average_price.py
[2023-03-03 12:17:24,384] {local_task_job.py:221} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-03-03 12:17:24,398] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1469. PIDs of all processes in the group: [1470, 1469]
[2023-03-03 12:17:24,399] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1469
[2023-03-03 12:17:24,401] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-03-03 12:17:24,403] {spark_submit.py:620} INFO - Sending kill signal to spark-submit
[2023-03-03 12:17:24,538] {process_utils.py:75} INFO - Process psutil.Process(pid=1469, status='terminated', exitcode=0, started='12:17:19') (1469) terminated with exit code 0
[2023-03-03 12:18:24,303] {process_utils.py:143} WARNING - process psutil.Process(pid=1470, name='java', status='zombie', started='12:17:20') did not respond to SIGTERM. Trying SIGKILL
[2023-03-03 12:18:24,306] {process_utils.py:80} INFO - Sending the signal Signals.SIGKILL to group 1469
